Survey added
nazar-goncharenko/SoftServe-course-backend pull request #27
Opened 2021-05-06 10:25 UTC by ViraMaximets

2021-05-07 10:32 UTC, Qvel requested changes

2021-05-07 10:32 UTC, Qvel commented on src/main/java/com/softserve/app/controller/CheckBoxController.java
> +    public List<CheckBox>  n(
dto?

2021-05-07 10:32 UTC, Qvel commented on src/main/java/com/softserve/app/controller/CheckBoxController.java
> +    public List<CheckBox>  n(
method name?

2021-05-07 10:32 UTC, Qvel commented on src/main/java/com/softserve/app/controller/SurveyController.java
> +        for (Survey s : surveys){
move logic to the service

2021-05-07 10:32 UTC, Qvel commented on src/main/java/com/softserve/app/controller/SurveyController.java
> +            if (!s.getIsOpen()) {
to the service

2021-05-11 18:12 UTC, Qvel requested changes

2021-05-12 06:14 UTC, ViraMaximets commented on src/main/java/com/softserve/app/models/View.java
> +public final class View {
i don`t ..

2021-05-12 06:48 UTC, ViraMaximets commented on pom.xml
> +            <groupId>javax.annotation</groupId>
used for postController

2021-05-12 06:50 UTC, ViraMaximets commented on src/main/java/com/softserve/app/constant/SportHubConstant.java
> +    JWT_EXCEPTION("Unable to get JWT Token or JWT Token has expired"),
this from old version of main..

2021-05-12 08:42 UTC, ViraMaximets commented on src/main/java/com/softserve/app/dto/SurveyDTO.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
important for angular

2021-05-18 07:31 UTC, Qvel approved these changes

2021-05-18 09:47 UTC, merged